### ISSUE TITLE
Ver 0.7 still report itself as 0.6

### ISSUE THREAD

**Issue by sinsinpub** [SuperIlu/jSH#3]
seems `JSH_VERSION` definitions have been forgotten to updated to 0.7.
so does doc html file. (tiny issue of doc index.html, 2 png files are missing in release package and pointed to absolute path, eg: `/doc/jSH.png`)

further suggestions:
* Introduce some method to terminate script execution in case of expected/unexpected infinite loop panic, like a Ctrl+C hotkey.
* API uses some unified naming convention, eg: lower camel case for method names, upper for class names, all lower case for namespaces/modules.
  * Perhaps, borrowing some designs from `NodeJS` API is not bad. Can make less modifications on codes written for node. eg: not only put `print` in global context, but also put into `console` module, linking to same functions like `console.log`/`console.info`
* Update MuJS to later version if possible. I failed to identify the ECMA-262 version of MuJS 1.05's implementation. It seems they added a test suite of ES5 in recent commit, so it's based on ES5.1 specification for latest version, I guess.

DOjS is awesome, and I like this out-of-box project either, because it makes javascript quick available for DOS and shipped with useful libraries. Looking forward for more nice native libraries or pure JS module libraries based on ES module system in future 👍

**Comment by sinsinpub** [comment]
new issue found in 0.7:
 * The `Exit(exitCode)` function displayed in readme not found in general module any more. The possible replacement function `Quit()` found, but exit code not acceptable.

**Comment by SuperIlu** [comment]
Hi, thanks for reporting. I took the liberty to split this issue up into several and I'll close this one.

Would you be willing and able to help with #8? My idea would be to add a Javascript module which provides the abstraction layer for NodeJS just like I did with p5js in DOjS.

As for updating MuJS: I took several attempt to update MUjS from 1.0.5 to never version. Last time I tried was 1.0.9. Sadly they changed the GC behavior and my previous fix for excessive memory consumption didn't work anymore.
Also I diffed both versions and couldn't find any major improvements to speed or functionality.
I will periodically re-visit that issue for DOjS as well as jSH...

**Comment by SuperIlu** [comment]
Also: where did you run jSH? Take a look at #5, it seems there is an issue with DOSBox and CTRL-C...
